### ISSUE TITLE
Allow for different years in different repos

### ISSUE THREAD

**Issue by kescobo** [SebRollen/AdventOfCode.jl#22]
The current default setup appears to be:

```
- advent
  - src
    - year1
    - year2
  - data
    - year1
    - year2
```

I much prefer

```
- advent
  - year1
    - src
    - data
  - year2
    - src
    - data
```

Are you willing to make this structure optional? Simplest would be to just have an option to omit the year from the path entirely, and leave the higher structure to the user. I'd be happy to make a PR

**Comment by SebRollen** [comment]
Hi,

Your proposed structure is much better than the current approach to be honest as it would allow us to add a test folder for each year at some point and run the tests for each year independently. I think we could make your proposed structure the default - feel free to open a pr or I might be able to work on it next weekend
